/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
              "primary-fixed": "#dae1ff",
              "caution-amber": "#FFB300",
              "on-primary": "#ffffff",
              "surface-variant": "#dbe1ff",
              "on-secondary-fixed-variant": "#005231",
              "surface-container-low": "#f3f3ff",
              "primary": "#0050cb",
              "surface-container": "#ebedff",
              "secondary-fixed": "#59fead",
              "midnight-slate": "#070D1E",
              "inverse-surface": "#282f49",
              "background": "#faf8ff",
              "on-secondary": "#ffffff",
              "surface-dim": "#d2d9fa",
              "primary-fixed-dim": "#b3c5ff",
              "surface-ice": "#F4F7FB",
              "on-error": "#ffffff",
              "on-tertiary-container": "#f9f7ff",
              "surface-container-lowest": "#ffffff",
              "secondary": "#006d43",
              "on-primary-container": "#f8f7ff",
              "error": "#ba1a1a",
              "on-error-container": "#93000a",
              "sensor-cyan": "#00F2FE",
              "on-background": "#131a33",
              "surface": "#faf8ff",
              "telemetry-emerald": "#00D084",
              "on-primary-fixed-variant": "#003fa4",
              "outline-variant": "#c2c6d8",
              "surface-container-highest": "#dbe1ff",
              "lidar-beam": "#4FACFE",
              "on-secondary-container": "#007146",
              "surface-tint": "#0054d6",
              "on-surface": "#131a33",
              "alert-crimson": "#FF3B30",
              "tertiary": "#515874",
              "surface-container-high": "#e3e7ff",
              "outline": "#727687",
              "secondary-container": "#56fbab",
              "inverse-on-surface": "#eff0ff",
              "on-tertiary": "#ffffff",
              "error-container": "#ffdad6",
              "surface-bright": "#faf8ff",
              "on-surface-variant": "#424656",
              "tertiary-fixed": "#dbe1ff",
              "inverse-primary": "#b3c5ff",
              "primary-container": "#0066ff",
              "secondary-fixed-dim": "#31e193",
              "tertiary-container": "#6a718e",
              "on-tertiary-fixed": "#131a33",
              "on-secondary-fixed": "#002111",
              "tertiary-fixed-dim": "#bec5e5",
              "on-tertiary-fixed-variant": "#3e4660",
              "surface-card": "#FFFFFF",
              "on-primary-fixed": "#001849"
      },
      borderRadius: {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      spacing: {
              "gutter-desktop": "1.5rem",
              "space-2xs": "0.25rem",
              "space-3xl": "4rem",
              "space-2xl": "3rem",
              "gutter-mobile": "1rem",
              "margin-mobile": "1.25rem",
              "margin-desktop": "3rem",
              "space-xl": "2rem",
              "space-lg": "1.5rem",
              "space-md": "1rem",
              "space-sm": "0.75rem",
              "space-xs": "0.5rem"
      },
      fontFamily: {
              "label-telemetry": ["JetBrains Mono", "monospace"],
              "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
              "headline-md": ["Plus Jakarta Sans", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
              "display-hero": ["Plus Jakarta Sans", "sans-serif"],
              "label-badge": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "button-text": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
              "label-telemetry": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
              "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
              "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
              "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
              "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
              "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
              "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
              "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
              "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
              "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
              "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
              "button-text": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
